### ISSUE TITLE
点击Complate后没有提交到输入框中

### ISSUE THREAD

**Issue by Typeve** [RedJue/git-commit-plugin#118]
![image](https://github.com/user-attachments/assets/d74af07f-988d-4e6b-8c30-fa82d523eb27)
现在暂时点击拷贝手动进行粘贴
我查看扩展宿主日志显示
```
TypeError: Cannot read properties of undefined (reading 'inputBox')
	at completeInputMessage (c:\Users\x\.vscode\extensions\redjue.git-commit-plugin-1.4.0\out\extension.js:134:18)
	at c:\Users\x\.vscode\extensions\redjue.git-commit-plugin-1.4.0\out\extension.js:153:25
```

**Comment by RedJue** [comment]
vscode 版本贴一下

**Comment by Typeve** [comment]
> vscode 版本贴一下
```
版本: 1.91.1 (user setup)
提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729
日期: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by TinyNing** [comment]
版本: 1.84.2 (user setup)
提交: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
日期: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

我这个版本也遇到了一样的问题

**Comment by RedJue** [comment]
好的 我修复一下

**Comment by RedJue** [comment]
版本: 1.92.1
提交: eaa41d57266683296de7d118f574d0c2652e1fc4
日期: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.5.0      这个版本我本地试了下没问题，可以更新下看看

**Comment by Typeve** [comment]
> 版本: 1.92.1 提交: eaa41d57266683296de7d118f574d0c2652e1fc4 日期: 2024-08-07T20:16:39.455Z Electron: 30.1.2 ElectronBuildId: 9870757 Chromium: 124.0.6367.243 Node.js: 20.14.0 V8: 12.4.254.20-electron.0 OS: Darwin x64 23.5.0
> 
> 这个版本我本地试了下没问题，可以更新下看看

我现在也是这个版本
`TypeError: Cannot read properties of undefined (reading 'inputBox')
	at completeInputMessage (c:\Users\x\.vscode\extensions\redjue.git-commit-plugin-1.4.0\out\extension.js:134:18)
	at c:\Users\x\.vscode\extensions\redjue.git-commit-plugin-1.4.0\out\extension.js:153:25`

**Comment by RedJue** [comment]
看来是 windows 的特定 bug，我排查看看

**Comment by Typeve** [comment]
重新加载窗口之后就正常了
我发现如何复现此问题了
1. 扩展列表
2. 禁用随意扩展
3. 重新启动扩展
然后git-commit-plugin扩展出现问题了

**Comment by RedJue** [comment]
应该还是 windows 的问题，mac 还是没法复现次问题
